-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 13:42:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_impacthub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_impacthub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_impacthub` DEFAULT CHARACTER SET utf8 ;
USE `db_impacthub` ;

-- -----------------------------------------------------
-- Table `db_impacthub`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_impacthub`.`tb_tema` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(1000) NULL,
  `nivel_urgencia` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_impacthub`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_impacthub`.`tb_usuario` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_impacthub`.`tb_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_impacthub`.`tb_post` (
  `id` BIGINT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(2000) NOT NULL,
  `localizacao` VARCHAR(255) NULL,
  `data` DATETIME NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `tema_id` BIGINT NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_post_tb_tema_idx` (`tema_id` ASC) VISIBLE,
  INDEX `fk_tb_post_tb_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_post_tb_tema`
    FOREIGN KEY (`tema_id`)
    REFERENCES `db_impacthub`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_post_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_impacthub`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
